<?php

namespace AppBundle\Repository;

/**
 * DateAndTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateAndTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
